#-------------------------------------------
# Plugin manager
#-------------------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  nnoremap <silent> <Space>I :call dein#install()<CR>
  nnoremap <silent> <Space>U :call dein#update()<CR>
'''

#-------------------------------------------
# Display
#-------------------------------------------
[[plugins]]
repo = 'dracula/vim'
hook_add = '''
  let g:dracula_italic = 0
  au MyAutoCmd VimEnter * nested colorscheme dracula
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  " タブラインの表示
  let g:airline#extensions#tabline#enabled = 1
  " （タブが一個の場合）バッファのリストをタブラインに表示する機能をオフ
  let g:airline#extensions#tabline#show_buffers = 0
  " 0でそのタブで開いてるウィンドウ数、1で左のタブから連番
  let g:airline#extensions#tabline#tab_nr_type = 1
  " パワーラインフォントの使用
  let g:airline_powerline_fonts = 1
  " 複数ウィンドウのときもステータスラインを分割しない
  let g:airline_inactive_collapse = 1
'''

#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'
#depends = 'vim-airline'
#hook_add = '''
#  let g:airline_theme = 'dracula'
#'''

#[[plugins]]
#repo = 'edkolev/tmuxline.vim'
#on_cmd = 'Tmuxline'

[[plugins]]
repo = 'simeji/winresizer'

#-------------------------------------------
# Asynchronous
#-------------------------------------------
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  let g:ale_lint_on_save = 1
  let g:ale_lint_on_text_changed = 0

  " vim-airline
  let g:airline#extensions#ale#enabled = 1
'''

#[[plugins]]
#repo = 'neomake/neomake'
#if = 'has("nvim")'
#hook_add = '''
#  autocmd! BufWritePost * Neomake
#
#  let g:neomake_open_list = 2
#  let g:neomake_error_sign = {'text': 'E>', 'texthl': 'Error'}
#  let g:neomake_warning_sign = {'text': 'W>', 'texthl': 'WarningMsg',}
#  let g:neomake_info_sign = {'text': 'I>', 'texthl': 'PmenuSel'}
#'''

#-------------------------------------------
# Text object
#-------------------------------------------
[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

#-------------------------------------------
# Operations
#-------------------------------------------
[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
  let g:NERDSpaceDelims = 1
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
  autocmd BufWritePre * :FixWhitespace
'''

#-------------------------------------------
# Others
#-------------------------------------------
[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
 let g:airline#extensions#tagbar#enabled = 1
 let g:airline_inactive_collapse = 0

 nnoremap <silent> <F8> :TagbarToggle<CR>
'''

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
