[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
#repo = 'dracula/vim'
repo = 'kota718/dracula-vim'
rev = 'develop'
hook_add = '''
  au MyAutoCmd VimEnter * nested colorscheme dracula
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

#[[plugins]]
#repo = 'neomake/neomake'
#if = 'has("nvim")'

[[plugins]]
repo = 'scrooloose/syntastic'
if = '!has("nvim")'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'honza/vim-snippets'


[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
  let g:NERDSpaceDelims = 1
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeShowHidden = 1

  nnoremap [nerdtree] <Nop>
  nmap <Leader>e [nerdtree]
  nnoremap <silent> [nerdtree]t :NERDTreeToggle<CR>
  nnoremap <silent> [nerdtree]f :NERDTreeFocus<CR>
'''

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap [fugitive] <Nop>
  nmap <Leader>g [fugitive]
  nnoremap [fugitive]d :<C-u>Gdiff<CR>
  nnoremap [fugitive]s :<C-u>Gstatus<CR>
  nnoremap [fugitive]l :<C-u>Glog<CR>
  nnoremap [fugitive]a :<C-u>Gwrite<CR>
  nnoremap [fugitive]c :<C-u>Gcommit<CR>
  nnoremap [fugitive]C :<C-u>Git commit --amend<CR>
  nnoremap [fugitive]b :<C-u>Gblame<CR>
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagbar', 'vim-fugitive']
hook_add = '''
  let g:airline#extensions#tabline#enabled = 1
  let g:airline_powerline_fonts = 1
'''

#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'
#depends = 'vim-airline'
#hook_add = '''
#  let g:airline_theme = 'dracula'
#'''

#[[plugins]]
#repo = 'edkolev/tmuxline.vim'
#on_cmd = 'Tmuxline'

[[plugins]]
repo = 'kassio/neoterm'
if = "has('nvim')"
hook_add = '''
  let g:neoterm_autoinsert = 1
  nnoremap <silent> <Space>t :Ttoggle<CR>
  tnoremap <silent> <ESC> <C-\><C-n>
'''

[[plugins]]
repo = 'wakatime/vim-wakatime'
