[[plugins]]
repo = 'Shougo/dein.vim'

# ===== color =====
[[plugins]]
repo = 'dracula/vim'

# ===== basic =====
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_start_level=2
let g:indent_guides_auto_colors=0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#444433 ctermbg=black
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#333344 ctermbg=darkgray
let g:indent_guides_guide_size = 1
'''

# ===== filer ======
[[plugins]]
repo = 'Shougo/denite.nvim'


# ===== powerline =====
[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagbar', 'vim-fugitive']
hook_add = '''
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' ' 
let g:airline#extensions#tabline#left_alt_sep = '|'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
let g:airline_theme = 'dracula'
'''

[[plugins]]
repo = 'edkolev/tmuxline.vim'
on_cmd = 'Tmuxline'

# ===== terminal =====
[[plugins]]
repo = 'kassio/neoterm'
if = "has('nvim')"

