[[plugins]]
repo = 'Shougo/dein.vim'

# ===== color =====
[[plugins]]
#repo = 'dracula/vim'
repo = 'sdemura/dracula-vim'
rev = 'fix_pmenu_colors'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme dracula
'''

# ===== basic =====
[[plugins]]
repo = 'Yggdroot/indentLine'

#[[plugins]]
#repo = 'neomake/neomake'
#if = 'has("nvim")'

[[plugins]]
repo = 'scrooloose/syntastic'
if = '!has("nvim")'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'honza/vim-snippets'


[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-surround'

# ===== filer ======
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_source = '''
  nnoremap <silent> <Space>e :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'tpope/vim-rails'

# ===== powerline =====
[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_source = '''
  nnoremap <Space>gd :<C-u>Gdiff<CR>
  nnoremap <Space>gs :<C-u>Gstatus<CR>
  nnoremap <Space>gl :<C-u>Glog<CR>
  nnoremap <Space>ga :<C-u>Gwrite<CR>
  nnoremap <Space>gc :<C-u>Gcommit<CR>
  nnoremap <Space>gC :<C-u>Git commit --amend<CR>
  nnoremap <Space>gb :<C-u>Gblame<CR>
'''


[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagbar', 'vim-fugitive']
hook_add = '''
  let g:airline#extensions#tabline#enabled = 1
  let g:airline_powerline_fonts = 1
'''

#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'
#depends = 'vim-airline'
#hook_add = '''
#  let g:airline_theme = 'dracula'
#'''

#[[plugins]]
#repo = 'edkolev/tmuxline.vim'
#on_cmd = 'Tmuxline'

# ===== terminal =====
[[plugins]]
repo = 'kassio/neoterm'
if = "has('nvim')"
hook_add = '''
  let g:neoterm_autoinsert = 1
'''
hook_source = '''
  nnoremap <silent> <Space>t :Ttoggle<CR>
'''

[[plugins]]
repo = 'wakatime/vim-wakatime'
